; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:lolin_c3_mini]
platform = espressif32
board = lolin_c3_mini
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries
monitor_speed = 115200
upload_protocol = esptool
upload_speed = 921600
build_flags = 
	-D ARDUINO_USB_CDC_ON_BOOT=1
	-D ARDUINO_USB_MODE=1
lib_deps = 
	gyverlibs/EncButton@^3.7.3
	adafruit/Adafruit MCP4725@^2.0.2
	adafruit/Adafruit ADS1X15@^2.5.0
	duinowitchery/hd44780@^1.3.2
	hmueller01/PubSubClient3@^3.1.0
	robtillaart/I2CKeyPad8x8@^0.3.1
